server:
  port: ${GATEWAY_PORT:8762}

eureka:
  instance:
    preferIpAddress: true
    hostname: ${EUREKA_HOSTNAME:localhost}

client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
    defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

spring:
  application:
    name: gatewayservice
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configuration:
          '[/**]':
            allowedOrigins: ${ALLOWED_ORIGINS:*}
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH

management:
  endpoint:
    gateway:
      enabled: ${GATEWAY_ROUTE_TABLES_ENABLED:true}
  endpoints:
    web:
      exposure:
        include: "*"